{{- if .Values.bindings.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    {{- include "ngrok-operator.labels" . | nindent 4 }}
  name: ngrok-intermediate-ca
  namespace: {{ .Release.Namespace }}
data:
  root.crt: |
    {{- .Values.bindings.ngrokCA | nindent 4 }}
{{- end }}
