name: Action - Changes
description: "Detect changes in the repository"

outputs:
  charts: ${{ steps.filter.outputs.charts }}
  chartyaml: ${{ steps.filter.outputs.chartyaml }}
  go: ${{ steps.filter.outputs.go }}
  tag: ${{ steps.filter.outputs.tag }}
  tests: ${{ steps.filter.outputs.tests }}
  make: ${{ steps.filter.outputs.make }}

runs:
  using: "composite"
  steps:
    - id: filter
      uses: dorny/paths-filter@v2.11.1
      with:
        filters: |
          chartyaml:
            - 'helm/ngrok-operator/Chart.yaml'
          charts:
            - 'helm/ngrok-operator/**'
            - 'scripts/e2e.sh'
          go:
            - '**.go'
            - 'go.mod'
            - 'go.sum'
            - 'cmd/**'
            - 'internal/**'
            - 'pkg/**'
            - 'Dockerfile'
            - 'scripts/e2e.sh'
            - 'VERSION'
          tests:
            - 'test/**'
          make:
            - 'Makefile'
          tag:
            - 'VERSION'
