name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

env:
  GO_VERSION: '1.23'
  DOCKER_BUILDX_PLATFORMS: linux/amd64,linux/arm64

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: "./.github/actions/changes.yaml"

  build-and-test:
    runs-on: ubuntu-latest
    needs:
    - changes
    - kubebuilder-diff
    if: |
      (needs.changes.outputs.go == 'true') ||
      (needs.changes.outputs.charts == 'true') ||
      (needs.changes.outputs.chartyaml == 'true') ||
      (needs.changes.outputs.tests == 'true') ||
      (needs.changes.outputs.make == 'true')
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
    - uses: "./.github/actions/build-and-test.yaml"
      with:
        run-e2e: true
        go-version: ${{ env.GO_VERSION }}
